I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/boss_scene.rpy", line 31, in script call
    call boss_attack
  File "game/boss_scene.rpy", line 68, in script call
    call choose1
  File "game/boss_scene.rpy", line 320, in script
    if d50 >= 26 and mc.hp > 0:
  File "game/boss_scene.rpy", line 322, in <module>
    elif d50 <= 25 and ww.hp > 0:
AttributeError: 'str' object has no attribute 'hp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/boss_scene.rpy", line 31, in script call
    call boss_attack
  File "game/boss_scene.rpy", line 68, in script call
    call choose1
  File "game/boss_scene.rpy", line 320, in script
    if d50 >= 26 and mc.hp > 0:
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/boss_scene.rpy", line 322, in <module>
    elif d50 <= 25 and ww.hp > 0:
AttributeError: 'str' object has no attribute 'hp'

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
not_yet_setted 1.0
Fri Nov 29 14:44:02 2024
